#include <iostream>
#include "polynom/polynom.h"
#include <complex>

using namespace pol;
using namespace std;


int main() {

	//cout << "Check float" << endl;
	//cout << "------------------" << endl;
	//Polynom <float> a(5);
	//a.set(5.2, 1);
	//a.set(1.5, 2);
	//float array[] = {1.4,2.7, 3.4,4.2};
	//Polynom <float> b (array, 4);
	//cout << a << endl;
	//cout << b << endl;
	//cout << "Sum +" << endl;
	//cout << "------------------" << endl;
	//Polynom <float> c = a + b;
	//cout << c << endl;
	//cout << "------------------" << endl;
	//cout << "Sum +=" << endl;
	//cout << "------------------" << endl;
	//a += b;
	//cout << a << endl;
	//cout << "------------------" << endl;
	//cout << "Minus -" << endl;
	//cout << "------------------" << endl;
	//c = a - b;
	//cout << c << endl;
	//cout << "------------------" << endl;
	//cout << "Minus -=" << endl;
	//cout << "------------------" << endl;
	//a -= c;
	//cout << a << endl;
	//cout << "------------------" << endl;
	//cout << "Operator []" << endl;
	//cout << "------------------" << endl;
	//cout << a[9] << endl;
	//cout << "------------------" << endl;
	//cout << "set []" << endl;
	//cout << "------------------" << endl;
	//a.set(7, 7);
	//cout << a << endl;
	//cout << "------------------" << endl;
	//cout << "expand" << endl;
	//cout << "------------------" << endl;
	//b.expand(12);
	//cout << b << endl;
	//cout << "------------------" << endl;
	//cout << "shrink_to_fit" << endl;
	//cout << "------------------" << endl;
	//b.shrink_to_fit();
	//cout << b << endl;
	//cout << "------------------" << endl;
	//cout << "multiply x" << endl;
	//cout << "------------------" << endl;
	//b = b * 5;
	//cout << b << endl;
	//cout << "------------------" << endl;
	//cout << "multiply x" << endl;
	//cout << "------------------" << endl;
	//b = 2 * b;
	//cout << b << endl;
	//cout << "------------------" << endl;
	//Polynom <float> copy(a);
	//if (copy == a) {
	//	cout << "genius" << endl;
	//}
	//cout << a << endl;
	//a.integrator();
	//cout << a << endl;

	/*cout << "Check int" << endl;
	cout << "------------------" << endl;
	Polynom <int> a(5);
	a.set(5, 1);
	a.set(1, 2);
	int array[] = { 1,2, 3,4 };
	Polynom <int> b(array, 4);
	cout << a << endl;
	cout << b << endl;
	cout << "Sum +" << endl;
	cout << "------------------" << endl;
	Polynom <int> c = a + b;
	cout << c << endl;
	cout << "------------------" << endl;
	cout << "Sum +=" << endl;
	cout << "------------------" << endl;
	b += a;
	cout << b << endl;
	cout << "------------------" << endl;
	cout << "Minus -" << endl;
	cout << "------------------" << endl;
	c = a - b;
	cout << c << endl;
	cout << "------------------" << endl;
	cout << "Minus -=" << endl;
	cout << "------------------" << endl;
	a -= c;
	cout << a << endl;
	cout << "------------------" << endl;
	cout << "Operator []" << endl;
	cout << "------------------" << endl;
	cout << a[9] << endl;
	cout << "------------------" << endl;
	cout << "set []" << endl;
	cout << "------------------" << endl;
	a.set(7, 7);
	cout << a << endl;
	cout << "------------------" << endl;
	cout << "expand" << endl;
	cout << "------------------" << endl;
	b.expand(12);
	cout << b << endl;
	cout << "------------------" << endl;
	cout << "shrink_to_fit" << endl;
	cout << "------------------" << endl;
	b.shrink_to_fit();
	cout << b << endl;
	cout << "------------------" << endl;
	cout << "multiply x" << endl;
	cout << "------------------" << endl;
	b = b * 5;
	cout << b << endl;
	cout << "------------------" << endl;
	cout << "multiply x" << endl;
	cout << "------------------" << endl;
	b = 2 * b;
	cout << b << endl;
	cout << "------------------" << endl;
	cout << a << endl;
	cout << "------------------" << endl;*/
	//cout << "integrator" << endl;
	//a.integrator();
	//cout << a << endl;

	cout << "Check Complex<float>" << endl;
	Polynom<std::complex<float>> a(5);
	std::complex<float> array[] = { complex<float>(1, 2), complex<float>(2, 3) };
	Polynom<std::complex<float>> b(array, 2);
	std::complex<float> c(1, 2);
	std::complex<float> g(3, 1);
	a.set(c, 0);
	a.set(g, 1);
	cout << a <<endl;
	cout << "----------------"<<endl;
	cout << b << endl;
	cout << "Sum +" << endl;
	cout << "------------------" << endl;
	Polynom<std::complex<float>> d=a+b;
	cout << d << endl;
	cout << "------------------" << endl;
	cout << "Sum +=" << endl;
	cout << "------------------" << endl;
	a += b;
	cout << a << endl;
	cout << "------------------" << endl;
	cout << "------------------" << endl;
	cout << "Minus -" << endl;
	cout << "------------------" << endl;
	d = a - b;
	cout << d << endl;
	cout << "------------------" << endl;
	cout << "Minus -=" << endl;
	cout << "------------------" << endl;
	a -= d;
	cout << a << endl;
	cout << "------------------" << endl;
	cout << "Operator []" << endl;
	cout << "------------------" << endl;
	cout << a[0] << endl;
	cout << "------------------" << endl;
	cout << "------------------" << endl;
	cout << "expand" << endl;
	cout << "------------------" << endl;
	b.expand(12);
	cout << b << endl;
	cout << "------------------" << endl;
	cout << "shrink_to_fit" << endl;
	cout << "------------------" << endl;
	b.shrink_to_fit();
	cout << b << endl;
	cout << "------------------" << endl;
	cout << "multiply x" << endl;
	cout << "------------------" << endl;
	b = b * 5;
	cout << b << endl;
	cout << "------------------" << endl;
	cout << "multiply x" << endl;
	cout << "------------------" << endl;
	b = 2 * b;
	cout << b << endl;
	cout << "------------------" << endl;
	complex<float> num(1, 2);
	cout << "multiply x" << endl;
	cout << "------------------" << endl;
	b = num * b;
	cout << b << endl;
	return 0;
}